### ISSUE TITLE
setup-ko@v0.6 broken, seems to be broken tar download link

### ISSUE THREAD

**Issue by Arkessler** [ko-build/setup-ko#38] opened 2024-10-24 18:20 UTC
Our GHA using setup-ko v0.6 broke as of an hour ago, seems to be an issue with the download link for the v0.17 tarball.

![image](https://github.com/user-attachments/assets/3fee8ce2-3088-493e-8894-cd39213dd7a3)

Visiting https://github.com/ko-build/ko/releases/download/v0.17.0/ko_0.17.0_Linux_x86_64.tar.gz directly returns a "Not Found"

I noticed the same error in the last action run for this repo too: https://github.com/ko-build/setup-ko/actions/runs/11504307780/job/32023514691

**Comment by emmahsax** [comment] 2024-10-24 18:31
I am also seeing the same error. Setting this in the GHA file allows installation, but clearly there is a further issue in v0.17.0.

```yaml
- uses: ko-build/setup-ko@v0.7
  with:
    version: v0.16.0
```

**Comment by soareswallace** [comment] 2024-10-24 18:37
Same thing here. The problem seems to be on v0.17.0, as @emmahsax said.

**Comment by cpanato** [comment] 2024-10-25 07:57
duplicate of https://github.com/ko-build/ko/issues/1433

fixed now

**Closed by cpanato** 2024-10-25 07:57 UTC
